name: moodtracker
description: "A new Flutter project."

publish_to: "none"

version: 1.0.1+4

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  gap: ^3.0.1
  uuid: ^4.5.1
  intl: ^0.20.2
  shared_preferences: ^2.5.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  mocktail: ^1.0.4
  easy_localization: ^3.0.7+1
  fl_chart: ^1.0.0
  firebase_core: ^3.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/translations/
    - assets/icons/
    - assets/samples/
    - test/assets/
