# workflow 이름
name: Test_GitHub_Actions

# 이벤트 정의
on:
  # main, develop 브랜치에 푸시될 때
  push:
    branches:
      - main
      - develop
  # main, develop 브랜치에 Pull Request가 생성될 때
  pull_request:
    branches:
      - main
      - develop

jobs:
  unit-test:
    name: Unit Test
    # 작업을 실행할 OS 정의
    runs-on: ubuntu-latest
    steps:
      # 하나의 step은 name과 uses/run으로 구성됨
      # name: step 이름
      # uses: 사용할 action(GitHub에서 제공하는 action)
      # run: 사용할 shell script
      - name: Chckout code
        # 레포지토리에서 코드를 가져옴
        uses: actions/checkout@v2

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.7.0"

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: dev

      - name: Import Flutter Packages
        run: |
          flutter pub get

      - name: Run Tests
        run: |
          flutter test --coverage
          # Generate coverage report
          genhtml coverage/lcov.info -o coverage/html
          # Upload coverage report to Codecov
          bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info -Z
