# workflow 이름
name: Test_GitHub_Actions

# 이벤트 정의
on:
  # main 브랜치에 푸시될 때
  push:
    branches:
      - main
  # main, develop 브랜치에 Pull Request가 생성될 때
  pull_request:
    branches:
      - main
      - develop

jobs:
  unit-test:
    name: Unit Test
    # 작업을 실행할 OS 정의
    runs-on: ubuntu-latest
    steps:
      # 하나의 step은 name과 uses/run으로 구성됨
      # name: step 이름
      # uses: 사용할 action(GitHub에서 제공하는 action)
      # run: 사용할 shell script
      - name: Chckout code
        # 레포지토리에서 코드를 가져옴
        uses: actions/checkout@v4

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: "stable"
          flutter-version: "3.32.1"

      - name: Import Flutter Packages
        run: |
          flutter pub get

      - name: Create dummy .env file for tests
        run: |
          echo "DUMMY_API_KEY=test_key" > .env
          echo "DUMMY_BASE_URL=http://localhost:8080" >> .env

      - name: Run Tests
        run: |
          flutter test
